### ISSUE TITLE
fails to call launchDummyTask function

### ISSUE THREAD

**Issue by moveforever** [dmlc/dmlc-core#133]
Hi, tianqi. I ran XGBoost on yarn. I have ran a test code:mushroom. My script's parameters is as followed:

```
 15     $WORK_DIR/dmlc-core/tracker/dmlc-submit \
 16         --cluster=yarn \
 17         --num-workers=2 \
 18         --num-servers=1 \
 19         --worker-cores=2 \
 20         --log-file="$log_file" \
 21         --ship-libcxx="/data0/zeus/soft/gcc/lib64" \
 22         --worker-memory=5g \
 23         --queue=root.zeus.zeus \
 24         --jobname=dmlc-xgboost \
 25         --hdfs-tempdir=ns1/user/zeus/xgboost \
 26         --log-level='DEBUG' \
 27         ../xgboost  \
 28         $CONF \
 29         data="hdfs://ns1/dw_ext/comm_rec/ctr/xgboost/test/train/agaricus.txt.train" \
 30         eval[test]="hdfs://ns1/dw_ext/comm_rec/ctr/xgboost/test/test/agaricus.txt.test" \
 31         model_dir="hdfs://ns1/dw_ext//comm_rec/ctr/xgboost/test/model"
```

When it calls launchDummyTask, it will run launcher.py without delivering any parameters. My yarn logs is as followed:

```
 LogType: stdout
 LogLength: 32
 Log Contents:
 Usage: launcher.py your command
```

**Comment by BaiGang** [comment]
What's in `$CONF`? Did it break the command line?

**Comment by moveforever** [comment]
It's listed as followed:
```
  2 # choose the booster, can be gbtree or gblinear
  3 booster = gbtree
  4 # choose logistic regression loss function for binary classification
  5 objective = binary:logistic
  6 
  7 # Tree Booster Parameters
  8 # step size shrinkage
  9 eta = 1.0
 10 # minimum loss reduction required to make a further partition
 11 gamma = 1.0
 12 # minimum sum of instance weight(hessian) needed in a child
 13 min_child_weight = 1
 14 # maximum depth of a tree
 15 max_depth = 3
 16 
 17 # Task Parameters
 18 # the number of round to do boosting
 19 num_round = 2
 20 # 0 means do not save any model except the final round model
 21 save_period = 0
 22 # The path of training data
 23 # The path of validation data, used to monitor training process, here [test] sets name of the validation set
 24 #eval[test] = "agaricus.txt.test" 
 25 # evaluate on training data as well each round
 26 eval_train = 1
 27 # The path of test data 
``

**Comment by moveforever** [comment]
There is an exception:
```
174 org.apache.hadoop.util.Shell$ExitCodeException:
175     at org.apache.hadoop.util.Shell.runCommand(Shell.java:501)
176     at org.apache.hadoop.util.Shell.run(Shell.java:418)
177     at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:655)
178     at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:287)
179     at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:300)
180     at org.apache.hadoop.yarn.server.nodemanager.containermanager.launch
```

**Comment by moveforever** [comment]
Hi BaiGang, in the affternoon I notice that it break in launch.py:line 76 which is as followed:
```
    ret = subprocess.call(args=sys.argv[1:], env=env)
    sys.exit(ret)
```
In the evening, I replaced check_call with call, and finally I found the bug is
```
18 LogType: stderr
 19 LogLength: 765
 20 Log Contents:
 21 ./xgboost: /usr/lib64/libgomp.so.1: version `GOMP_4.0' not found (required by ./xgboost)
 22 Traceback (most recent call last):
 23   File "./launcher.py", line 83, in <module>
 24     main()
 25   File "./launcher.py", line 78, in main
 26     ret = subprocess.check_call(args=sys.argv[1:], env=env)
 27   File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
 28     raise CalledProcessError(retcode, cmd)
```
