### ISSUE TITLE
dmlc-submit does not recognize ssh as cluster type?

### ISSUE THREAD

**Issue by CodingCat** [dmlc/dmlc-core#137]
```

dmlc-core/tracker/dmlc-submit --cluster ssh --num-workers 2 xgboost demo/binary_classification/mushroom.conf data=demo/data/agaricus.txt.train eval=demo/data/agaricus.txt.test 
Traceback (most recent call last):
  File "dmlc-core/tracker/dmlc-submit", line 9, in <module>
    submit.main()
  File "/Users/nanzhu/code/xgboost/dmlc-core/tracker/dmlc_tracker/submit.py", line 50, in main
    raise RuntimeError('Unknown submission cluster type %s' % args.cluster)
RuntimeError: Unknown submission cluster type ssh

```

**Comment by tqchen** [comment]
ssh used to sit on @mli 's pslite repo and may not have been moved yet
