### ISSUE TITLE
The error in dmlc-core/tracker/dmlc_tracker/tracker.py

### ISSUE THREAD

**Issue by yxzf** [dmlc/dmlc-core#160]
@Earthson
I cloned the code today, and test the dmlc-submit, but find this error

sh run_xgboost.sh
Traceback (most recent call last):
  File "/opt/meituan/xgboost/dmlc-core/tracker/dmlc-submit", line 7, in <module>
    from dmlc_tracker import submit
  File "/opt/meituan/xgboost/dmlc-core/tracker/dmlc_tracker/submit.py", line 6, in <module>
    from . import local
  File "/opt/meituan/xgboost/dmlc-core/tracker/dmlc_tracker/local.py", line 10, in <module>
    from . import tracker
  File "/opt/meituan/xgboost/dmlc-core/tracker/dmlc_tracker/tracker.py", line 149
    if e.errno in {98, 48}:
                            ^
SyntaxError: invalid syntax

**Comment by Earthson** [comment]
@yxzf what is your python version? It seems to be your python does not support "{}"

you could change {98, 48} to [98, 48].

**Comment by Earthson** [comment]
@yxzf I've changed some code to support Python 2.7&3.5. (Python 2.7.12 & 3.5.1 tested). Python 2.6 has no support to this set literal which is my mistake:)

**Comment by Earthson** [comment]
@yxzf Could you test it and prepare a PR? I'm on a business trip.

**Comment by yxzf** [comment]
@Earthson I have changed it to [98, 48], now it's OK. And I make a Pull Request.

**Comment by AbdealiJK** [comment]
Was fixed in https://github.com/dmlc/dmlc-core/commit/5c36a2c0f79c0f6082e1d20e0feaf0efe5080d0d
This issue can be closed ?
